# Generated by Django 5.0.6 on 2024-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
