# Generated by Django 5.0.6 on 2024-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="slug",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
