# Generated by Django 5.0.6 on 2024-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_adminprofile_user_alter_customerprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="public",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
