# Generated by Django 5.0.6 on 2024-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
