# Generated by Django 5.0.6 on 2024-07-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0004_alter_chatroom_receiver"),
        ("profiles", "0002_alter_customerprofile_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatroom_receiver",
                to="profiles.customerprofile",
            ),
        ),
    ]
