# Generated by Django 5.0.6 on 2024-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0005_alter_chatroom_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="url_serve",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
