version: '3.10'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "/scripts/start.sh"
    expose:
      - '8000'
    networks:
      - core_network
    volumes:
      - ./core:/core
      - static-data:/vol/web
      - ./scripts/start.sh:/scripts/start.sh
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.0-alpine3.16
    restart: always
    env_file:
      - ./core/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

  celery:
    container_name: celery
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c
      "celery -A core worker -l info"
    env_file:
      - ./core/.env
    volumes:
      - ./core:/core
    depends_on:
      - rabbitmq
      - backend

  celery-beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c
      "celery -A core beat -l info"
    volumes:
      - ./core:/core
    env_file:
      - ./core/.env
    depends_on:
      - rabbitmq
      - backend
    restart: always


volumes:
  static-data:
  postgres-data:


networks:
  core_network:
