# Generated by Django 5.0.6 on 2024-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("update_datetime", models.DateTimeField(auto_now=True)),
                ("accepted", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connection",
                "default_related_name": "connections",
            },
        ),
    ]
